### PR TITLE
Gtk::Application

### PR DESCRIPTION
**Pull request by benwaffle**
This adds a clean, non-bloated entry point (and removes the old one). It also runs only one instance of  the app and handles activate signals (app was run so create a new window) and open signals (open a file in gTorrent). We can later remove the single-process code from -core.

### CODE REVIEW

**Comment by benwaffle** [comment]
what do you think?

**Comment by IGI-111** [comment]
Well i know the code is there, but since this is a rewrite could you elaborate on what it is that you added/rewrote?
What did the Application Class didn't do that the current model does?

**Comment by benwaffle** [comment]
This is `Application`:
```C++
class Application
{
private:
	std::shared_ptr<gt::Core> m_core;
	std::shared_ptr<GuiBase> m_gui;
public:
	static std::shared_ptr<Application> getSingleton();
	std::shared_ptr<gt::Core> &getCore();
	int run(int argc, char **argv);
};
```

Currently, `main` calls `Application::getSingleton()->run(argc, argv);`. Application is a singleton that just holds a `gt::Core` and a `GuiBase`. Besides `loadDefaultSettings()`, `GuiBase` just has a virtual run method. Then, we have `GuiGtk` which subclasses `GuiBase` and actually loads the UI. I've compressed everything into a single class, `GTorrentApp`.

Besides removing these useless tiny classes, I've also subclassed `Gtk::Application`. The philosophy of `Gtk::Application` is that `main` is not important. Instead, we handle `startup`, `activate`, and `open` signals. `Gtk::Application` ensures that only one instance of the app is running.
- Running `./gtorrent-gtk` the first time sends the `startup` and `activate` signals.
- Running `./gtorrent-gtk` when another instance is already running will send an `activate` signal to the first process (so we can open a new window or something) and immediately exit.
- When the user opens a file with gTorrent (from a file manager or browser), the existing process receives the `open` signal.

**Comment by nyanpasu** [comment]
Why are you subclassing `Gtk::Application`?

**Comment by benwaffle** [comment]
That's what you're supposed to do. The virtual functions are the signal handlers.

**Comment by benwaffle** [comment]
See http://a.pomf.se/tbizng.webm

**Comment by nyanpasu** [comment]
lol

**Pull request closed without merging**
